import io
import logging

import pytest

from crocodeel.conta_event import (
    ContaminationEvent,
    ContaminationEventIO,
    round_conta_rate,
)
from crocodeel.exceptions import InputDataError


def test_contamination_event_defaults():
    """Test default values of a contamination event."""
    event = ContaminationEvent(
        source="source",
        target="target",
    )

    assert event.source == "source"
    assert event.target == "target"
    assert event.rate == 0.0
    assert event.probability == 0.0
    assert not event.conta_line_species


@pytest.mark.parametrize(
    "rate, expected",
    [
        (0, 0),
        (0.000123456, 0.000123),
        (0.00123456, 0.00123),
        (0.0123456, 0.0123),
        (0.123456, 0.123),
        (0.9999, 1.00),
    ],
)
def test_round_conta_rate(rate, expected):
    """Test rounding contamination rates to three significant digits."""
    assert round_conta_rate(rate) == pytest.approx(expected)


@pytest.mark.parametrize(
    "rate, significant_digits, expected",
    [
        (0.00123456, 2, 0.0012),
        (0.00123456, 3, 0.00123),
        (0.00123456, 4, 0.001235),
        (0.123456, 2, 0.12),
        (0.123456, 3, 0.123),
        (0.123456, 4, 0.1235),
        (0.99999, 2, 1.0),
        (0.99999, 3, 1.0),
        (0.99999, 4, 1.0),
    ],
)
def test_round_conta_rate_significant_digits(
    rate,
    significant_digits,
    expected,
):
    """Test rounding with different numbers of significant digits."""
    assert round_conta_rate(rate, significant_digits) == pytest.approx(expected)


@pytest.mark.parametrize(
    "rate, expected",
    [
        (0.0009999, 0.001),
        (0.009999, 0.01),
        (0.09999, 0.1),
        (0.9999, 1.0),
    ],
)
def test_round_conta_rate_magnitude_boundaries(rate, expected):
    """Test rounding across orders of magnitude."""
    assert round_conta_rate(rate) == pytest.approx(expected)


def test_round_conta_rate_zero():
    """Test that zero is returned unchanged."""
    assert round_conta_rate(0) == 0


def test_read_tsv(caplog):
    """Test reading contamination events from a TSV file."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\t0.99\tspecies1,species2\n"
        "sample3\tsample4\t0.01\t0.85\tspecies3\n"
    )
    tsv.name = "contamination_events.tsv"

    with caplog.at_level(logging.INFO):
        events = ContaminationEventIO.read_tsv(tsv)

    assert len(events) == 2

    assert events[0].source == "sample1"
    assert events[0].target == "sample2"
    assert events[0].rate == pytest.approx(0.05)
    assert events[0].probability == pytest.approx(0.99)
    assert events[0].conta_line_species == ["species1", "species2"]

    assert events[1].source == "sample3"
    assert events[1].target == "sample4"
    assert events[1].rate == pytest.approx(0.01)
    assert events[1].probability == pytest.approx(0.85)
    assert events[1].conta_line_species == ["species3"]

    assert "2 contamination events loaded" in caplog.text


def test_read_tsv_skips_comments():
    """Test that comment lines are ignored when reading a TSV."""
    tsv = io.StringIO(
        "# CroCoDeEL contamination events\n"
        "# Generated by CroCoDeEL\n"
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\t0.99\tspecies1,species2\n"
    )
    tsv.name = "contamination_events.tsv"

    events = ContaminationEventIO.read_tsv(tsv)

    assert len(events) == 1
    assert events[0].source == "sample1"
    assert events[0].target == "sample2"


def test_read_tsv_rejects_missing_columns():
    """Test that missing required columns are rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\n"
        "sample1\tsample2\t0.05\t0.99\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="missing required column.*contamination_specific_species",
    ):
        ContaminationEventIO.read_tsv(tsv)


def test_read_tsv_rejects_empty_file():
    """Test that an empty contamination events file is rejected."""
    tsv = io.StringIO("")
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="empty or has no header",
    ):
        ContaminationEventIO.read_tsv(tsv)


def test_read_tsv_rejects_empty_source():
    """Test that an empty source sample is rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "\tsample2\t0.05\t0.99\tspecies1\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="Missing source sample",
    ):
        ContaminationEventIO.read_tsv(tsv)


def test_read_tsv_rejects_empty_target():
    """Test that an empty target sample is rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\t\t0.05\t0.99\tspecies1\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="Missing target sample",
    ):
        ContaminationEventIO.read_tsv(tsv)


def test_read_tsv_rejects_empty_contamination_specific_species():
    """Test that empty contamination-specific species are rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\t0.99\t\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="Missing contamination-specific species",
    ):
        ContaminationEventIO.read_tsv(tsv)


@pytest.mark.parametrize(
    "rate",
    [
        -0.1,
        1.1,
        float("nan"),
        float("inf"),
        -float("inf"),
    ],
)
def test_read_tsv_rejects_invalid_rate(rate):
    """Test that invalid contamination rates are rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        f"sample1\tsample2\t{rate}\t0.99\tspecies1\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(InputDataError):
        ContaminationEventIO.read_tsv(tsv)


def test_read_tsv_rejects_non_numeric_rate():
    """Test that non-numeric contamination rates are rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\tfoo\t0.99\tspecies1\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="Invalid rate",
    ):
        ContaminationEventIO.read_tsv(tsv)


@pytest.mark.parametrize(
    "probability",
    [
        -0.1,
        1.1,
        float("nan"),
        float("inf"),
        -float("inf"),
    ],
)
def test_read_tsv_rejects_invalid_probability(probability):
    """Test that invalid contamination probabilities are rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        f"sample1\tsample2\t0.05\t{probability}\tspecies1\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(InputDataError):
        ContaminationEventIO.read_tsv(tsv)


def test_read_tsv_rejects_non_numeric_probability():
    """Test that non-numeric probabilities are rejected."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\tfoo\tspecies1\n"
    )
    tsv.name = "contamination_events.tsv"

    with pytest.raises(
        InputDataError,
        match="Invalid probability",
    ):
        ContaminationEventIO.read_tsv(tsv)


def test_write_tsv():
    """Test writing contamination events to TSV."""
    events = [
        ContaminationEvent(
            source="sample1",
            target="sample2",
            rate=0.05,
            probability=0.99,
            conta_line_species=["species1", "species2"],
        ),
        ContaminationEvent(
            source="sample3",
            target="sample4",
            rate=0.01,
            probability=0.85,
            conta_line_species=["species3"],
        ),
    ]

    output = io.StringIO()
    output.name = "contamination_events.tsv"

    ContaminationEventIO.write_tsv(events, output)

    assert output.getvalue() == (
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t5.00e-02\t0.99\tspecies1,species2\n"
        "sample3\tsample4\t1.00e-02\t0.85\tspecies3\n"
    )


def test_tsv_round_trip():
    """Test that events can be written and read back."""
    events = [
        ContaminationEvent(
            source="sample1",
            target="sample2",
            rate=0.05,
            probability=0.99,
            conta_line_species=["species1", "species2"],
        ),
        ContaminationEvent(
            source="sample3",
            target="sample4",
            rate=0.01,
            probability=0.85,
            conta_line_species=["species3"],
        ),
    ]

    output = io.StringIO()
    output.name = "contamination_events.tsv"

    ContaminationEventIO.write_tsv(events, output)

    output.seek(0)

    loaded_events = ContaminationEventIO.read_tsv(output)

    assert loaded_events == events
