import io
import logging

import pytest

from crocodeel.conta_event import (
    ContaminationEvent,
    ContaminationEventIO,
)


def test_contamination_event_defaults():
    """Test default values of a contamination event."""
    event = ContaminationEvent(
        source="source",
        target="target",
    )

    assert event.source == "source"
    assert event.target == "target"
    assert event.rate == 0.0
    assert event.probability == 0.0
    assert not event.conta_line_species


def test_read_tsv(caplog):
    """Test reading contamination events from a TSV file."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\t0.99\tspecies1,species2\n"
        "sample3\tsample4\t0.01\t0.85\tspecies3\n"
    )

    # StringIO does not have a useful name attribute, while read_tsv()
    # uses fh.name for logging.
    tsv.name = "contamination_events.tsv"

    with caplog.at_level(logging.INFO):
        events = ContaminationEventIO.read_tsv(tsv)

    assert len(events) == 2

    assert events[0].source == "sample1"
    assert events[0].target == "sample2"
    assert events[0].rate == pytest.approx(0.05)
    assert events[0].probability == pytest.approx(0.99)
    assert events[0].conta_line_species == ["species1", "species2"]

    assert events[1].source == "sample3"
    assert events[1].target == "sample4"
    assert events[1].rate == pytest.approx(0.01)
    assert events[1].probability == pytest.approx(0.85)
    assert events[1].conta_line_species == ["species3"]

    assert "2 contamination events loaded" in caplog.text


def test_read_tsv_skips_comments():
    """Test that comment lines are ignored when reading a TSV."""
    tsv = io.StringIO(
        "# CroCoDeEL contamination events\n"
        "# Generated by CroCoDeEL\n"
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\t0.99\tspecies1,species2\n"
    )
    tsv.name = "contamination_events.tsv"

    events = ContaminationEventIO.read_tsv(tsv)

    assert len(events) == 1
    assert events[0].source == "sample1"
    assert events[0].target == "sample2"


def test_read_tsv_empty_species_list():
    """Test reading an event without contamination-specific species."""
    tsv = io.StringIO(
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t0.05\t0.99\t\n"
    )
    tsv.name = "contamination_events.tsv"

    events = ContaminationEventIO.read_tsv(tsv)

    assert len(events) == 1
    assert events[0].conta_line_species == []


def test_write_tsv():
    """Test writing contamination events to TSV."""
    events = [
        ContaminationEvent(
            source="sample1",
            target="sample2",
            rate=0.05,
            probability=0.99,
            conta_line_species=["species1", "species2"],
        ),
        ContaminationEvent(
            source="sample3",
            target="sample4",
            rate=0.01,
            probability=0.85,
            conta_line_species=["species3"],
        ),
    ]

    output = io.StringIO()
    output.name = "contamination_events.tsv"

    ContaminationEventIO.write_tsv(events, output)

    assert output.getvalue() == (
        "source\ttarget\trate\tprobability\t"
        "contamination_specific_species\n"
        "sample1\tsample2\t5.00e-02\t0.99\tspecies1,species2\n"
        "sample3\tsample4\t1.00e-02\t0.85\tspecies3\n"
    )

def test_tsv_round_trip():
    """Test that events can be written and read back."""
    events = [
        ContaminationEvent(
            source="sample1",
            target="sample2",
            rate=0.05,
            probability=0.99,
            conta_line_species=["species1", "species2"],
        ),
        ContaminationEvent(
            source="sample3",
            target="sample4",
            rate=0.01,
            probability=0.85,
            conta_line_species=["species3"],
        ),
    ]

    output = io.StringIO()
    output.name = "contamination_events.tsv"

    ContaminationEventIO.write_tsv(events, output)

    output.seek(0)

    loaded_events = ContaminationEventIO.read_tsv(output)

    assert loaded_events == events
