channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - nextflow
  - pandas
  - numpy
  - joblib
  - scipy
  - scikit-learn=1.3
  - plotnine=0.12
  - matplotlib
  - patchworklib
  - seaborn
