{% set name = "crocodeel" %}
{% set version = "1.0.0" %}

package:
    name: {{ name }}
    version: {{ version }}


source:
  url: https://github.com/metagenopolis/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0b95045f8466c6f45bb73f8d6f5fccad29e6a5a01217489643dc8fedce099a9a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage('crocodeel', max_pin="x.x") }}

requirements:
    host:
        - python >=3.12
        - poetry
    run:
        - python >=3.12
        - pandas >=2.2
        - numpy >=1.26
        - joblib >=1.4
        - scipy >=1.13
        - scikit-learn ==1.3.0
        - matplotlib-base >=3.8
        - tqdm >=4.66

test:
    commands:
        - crocodeel -h

about:
  home: https://github.com/metagenopolis/crocodeel
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: 'CroCoDeEL is a tool that detects cross-sample contamination in shotgun metagenomic data'
  description: |
    CroCoDeEL is a tool that detects cross-sample (aka well-to-well) contamination in shotgun metagenomic data.
    It accurately identifies contaminated samples but also pinpoints contamination sources and estimates contamination rates.
    CroCoDeEL relies only on species abundance tables and does not need negative controls.
  license_family: GPL3
