{% set name = "crocodeel" %}
{% set version = "1.0.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    path: ..

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
    host:
        - python=3.11.3
        - nextflow
    run:
        - python=3.11.3
        - sys
        - os
        - pandas
        - numpy
        - argparse
        - joblib
        - scipy
        - scikit-learn
        - plotnine
        - matplotlib
        - patchworklib

about:
  home: https://forgemia.inra.fr/metagenopolis/crocodeel
        