name: GitLab mirroring

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:metagenopolis/CroCoDeEL.git"
          destination-repo: "git@forge.inrae.fr:metagenopolis/crocodeel.git"

