name: Publish crocodeel

on:
  release:
    types: [created]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
      - name: Build and publish to PyPI
        run: |
          poetry config http-basic.pypi __token__ ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish --skip-existing
