name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --with test,mypy,pylint

      - name: Run tests
        run: poetry run pytest -v --cov=crocodeel --cov-report=xml

      - name: Run mypy
        run: poetry run mypy crocodeel

      - name: Run pylint
        run: poetry run pylint --disable=R crocodeel

      - name: Run installation test
        run: poetry run crocodeel self_test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
